name: Build

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  dpdm:
    runs-on: ubuntu-latest
    env:
      CI: true
      NODE_AUTH_TOKEN: ${{ secrets.GPR_ACCESS_TOKEN }}

    steps:
      - name: 🛎 Checkout
        uses: actions/checkout@v5

      - name: 🟩 Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '18.20.4'
          registry-url: https://npm.pkg.github.com/
          scope: '@unosquare'
          cache: 'npm'

      - name: 🤠 npm install
        run: npm ci

      - name: 💅 Prettier
        run: npm run prettier

      - name: 🎠 Test
        run: npm test

      - name: 🏗 Build
        run: npm run build