name: Lint PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:    
    uses: unosquare/bump-npm-version/.github/workflows/lint.yml@master
    with:
      node-version: '18.20.4'
    secrets:
      github-token: ${{ secrets.GPR_ACCESS_TOKEN }}
