name: npm Publish

on:
  push:
    branches: master

jobs:
  publish:
    uses: unosquare/bump-npm-version/.github/workflows/publish-public.yml@master
    with:
      node-version: '18.20.4'
    secrets:
      github-token: ${{ secrets.GPR_ACCESS_TOKEN }}
      npm-token: ${{ secrets.NPM_TOKEN }}
